# This workflow covers building output applications and associated artifacts.
name: build-all

on:
  workflow_dispatch: # lets you run a build from the UI
  push:
  #pull_request:

# When pushing new commits, cancel any running builds on that branch
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

defaults:
  run:
    shell: bash

jobs:
  build-daw:
    name: daw ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # show all errors for each platform (vs. cancel jobs on error)
      matrix:
        include:
          - name: Linux
            os: ubuntu-24.04
            extra-flags:
          #- name: macOS
          #  os: macos-14
          #  extra-flags: -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" -DKITSBLIPS_ENABLE_VST="OFF"
          - name: Windows
            os: windows-2025
            extra-flags:

    steps:
      - name: Set up Linux deps
        if: runner.os == 'Linux'
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libsdl2-dev libxtst-dev libcurl-dev
          version: 1.0

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: ./.github/actions/cmake
        env:
          KITSBLIPS_SENTRY_DSN: ${{ secrets.KITSBLIPS_SENTRY_DSN }}
        with:
          source: ${{github.workspace}}/daw
          build: ${{github.workspace}}/build
          extra-flags: ${{matrix.extra-flags}}

      - name: Package
        uses: actions/upload-artifact@v4
        with:
          name: KitsBlips-DAW-${{ matrix.name }}
          path: ${{github.workspace}}/build/dist

  build-vcvrack:
    name: vcvrack ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # show all errors for each platform (vs. cancel jobs on error)
      matrix:
        include:
          - name: Linux
            os: ubuntu-22.04
            extra-flags: -G "Unix Makefiles"
          - name: macOS x86_64
            os: macos-14
            extra-flags: -G "Unix Makefiles" -DCMAKE_OSX_ARCHITECTURES="x86_64"
          - name: macOS arm64
            os: macos-14
            extra-flags: -G "Unix Makefiles" -DCMAKE_OSX_ARCHITECTURES="arm64"
          - name: Windows
            os: windows-2025
            extra-flags: -G "MinGW Makefiles"
    steps:
      - name: Set up MinGW
        if: runner.os == 'Windows'
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64
          static: 0

      - name: Set up Linux deps
        if: runner.os == 'Linux'
        # https://github.com/VCVRack/rack-plugin-toolchain/blob/v2/Makefile#L268
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: ca-certificates git build-essential autoconf automake bison flex gawk libtool-bin libncurses5-dev unzip zip jq libgl-dev libglu-dev git wget curl cmake nasm xz-utils file python3 libxml2-dev libssl-dev texinfo help2man libz-dev rsync xxd perl coreutils zstd markdown libarchive-tools
          version: 1.0

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: ./.github/actions/cmake
        with:
          source: ${{github.workspace}}/vcvrack
          install: ${{github.workspace}}/dist
          extra-flags: ${{matrix.extra-flags}}

      - name: Package
        uses: actions/upload-artifact@v4
        with:
          name: KitsBlips-VCVRack-${{ matrix.name }}
          path: ${{github.workspace}}/dist

  build-daisy:
    name: daisy ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # show all errors for each platform (vs. cancel jobs on error)
      matrix:
        include:
          - name: Linux
            os: ubuntu-22.04
    steps:
      - name: Setup arm-none-eabi-gcc
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: "9-2019-q4"

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: ./.github/actions/cmake
        with:
          source: ${{github.workspace}}/daisy
          install: ${{github.workspace}}/dist

      - name: Package
        uses: actions/upload-artifact@v4
        with:
          name: KitsBlips-Daisy
          path: ${{github.workspace}}/dist
